### ISSUE TITLE
Ofertas Kernel

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#100]
[Kernel Job Offers - Pycon.pdf](https://github.com/python-spain/PyConES-2018/files/2422925/Kernel.Job.Offers.-.Pycon.pdf)

**Comment by saruba** [comment]
Nos faltaría un email para enviar las solicitudes, no?

**Comment by astrojuanlu** [comment]
jobs@kernel-analytics.com
