### ISSUE TITLE
Últimos retoques agenda

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#112]
Charlas que no se impartirán (seguro):

* Find Vulnerability on Your Python Code, sábado 15:00
* Python Espacial, domingo 15:30

Y hay muchos huecos de charlas patrocinadas sin rellenar.

Yo creo que lo mejor es que quitemos 3 charlas del final del sábado, para adelantar las rápidas y que se haga menos pesado el primer día (además de dar más tiempo a la asamblea). Y juntar los huecos que sobren uno a continuación del otro por si surge un open space (?). ¿Cómo lo ves @javipalanca?

**Comment by astrojuanlu** [comment]
Charla extra 1: Un drone voló sobre el nido de Python 
Autor: Mario Bartolome Manovel
Resumen: En 2014 construí mi primer drone. Algo que empezó como un hobby, es hoy parte de mi proyecto de final de carrera. Haciendo uso de Python tanto para back como frontend y una RaspberryPi, he diseñado un sistema que permite controlar un drone a través de una interfaz web realizando streaming de vídeo.


Bio: 

---

Hola! Me llamo Mario, 

Soy un **apasionado** y un curioso de la informática y la electrónica. Sobre todo de la seguridad, y los drones.
Llevo casi 4 años construyendo y volando drones, cacharreando con todo lo relacionado con seguridad informática desde hace varios años, y desmontando trastos desde que puedo sostener un destornillador *(**recuerda**, si lo desmontas, montas de nuevo, sobran tornillos pero aún así funciona, entonces lo has mejorado. Ahora pesa menos)*

 Si te interesa la experiencia laboral, te diré que...

* trabajé durante casi 4 años en una empresa dedicada la sector energético, como Piloto y Técnico en Electrónica de Sistemas Submarinos no tripulados, en  varios sitios, como China, Brasil, Noruega, Italia, Holanda...
* he trabajado como técnico de sitemas y de help-desk en el Hospital Universitario de Burgos.

Si te interesan los títulos y cualificaciones, te diré que...

* soy Técnico Superior en Sistemas de Telecomunicaciones e Informáticos.
* soy Graduado en Ingeniería en Informática por la Universidad de Burgos.
* hablo y escribo inglés con nivel casi nativo, casi 4 años por el mundo ayudan mucho!

---

#### Un **drone**, una **RaspberryPi**, una **cámara con visión nocturna**, una **web diseñada mediante Flask** que permite controlar ese drone de forma totalmente remota, y desde cualquier lugar del mundo... y todo ello bien conectado por el lenguaje que hoy nos ha traido aquí:
![PYTHON](https://www.python.org/static/community_logos/python-logo.png "Python")

#### Sí... Pocas palabras juntas podrían atraer tanta atención. 

---
**¿Te gusta(n)...**

* ...programar en **Python**?
Menuda pregunta, si no ¿qué ibas a hacer aquí?

* ...los **drones**?
Menuda pregunta, ¿a quién no?

* ...las **RaspberryPi**? 
    Deme diez, pero démelas ya.

* ...las enumeraciones interminables?

Esta charla es un ejemplo perfecto de **que** se puede conseguir con Python. Una implementación que pasa de la simple teoría a algo real, tremendamente divertido, y potencialmente peligroso **:D**.

En esta charla se mostrará como se han integrado diferentes tecnologías mediante Python, para conseguir controlar un drone conectado a una RaspberryPi.

---

### Hablaremos de...

### Flask

Utilizado en el diseño y gestión de la página web, así como de SQLAlchemy para mantener la base de datos, Flask-SocketIO para comunicación en tiempo real con WebSockets y otros módulos compatibles con este pequeño gran framework.

#### WebSockets

Un poco de JavaScript para ayudarnos a comunicar el input de usuario con la aplicación web basada en Flask.

#### WebRTC

Una de las tecnologías más prometedoras para el **streaming de video en riguroso directo**, y con una latencia mínima. 

### Python

#### Comunicación Serie

De alguna forma se tiene que **establecer comunicación entre la RaspberryPi y el drone**, y Python provee de mecanismos que permiten implementar un protocolo de comunicación muy avanzado, de forma relativamente sencilla.

#### Threads y Sockets

Hay que mantener ese **servidor de control remoto** constántemente atento y listo para recibir órdenes!

#### Numpy

Utilizado para implemnetar un sistema de **evasión de obstáculos** de forma eficiente, y un sistema de **localización sin GPS**, basando ambos en las posibilidades del cálculo vectorizado que ofrece Numpy.

---

### Y por supuesto...

`DEMO || GT*O`

### Demo!

Para la admiración, sorpresa y/o terror (no son excluyentes) de los asistentes, se llevará a cabo una pequeña demo en la que se hará volar un drone basado en el sistema expuesto. Siempre contemplando una serie de medidas de seguridad, por supuesto.

### Ronda de preguntas

**Comment by astrojuanlu** [comment]
Charla extra 2 **provisional**: From chaos to insights: the challenges of extracting meaningful information from unstructured data with Python and spaCy
Autor: Jeson Jacob 
Resumen: The majority of textual data relevant to companies today is unstructured data (PDF,HTML,tweets,etc). Extracting meaningful insights from this chaos is a daunting task. We will share how we built a data product in Python with spaCy at its core, and the lessons and best practices learnt along the way.
Description: 

Helping companies to be better citizens of the world means providing them with information about a myriad of issues such as Human Rights, Diversity, Climate Change, Carbon Emissions, etc., and helping them prioritise the different signals. For us Python developers and data scientists, this means working with thousands of sources of different types (PDF, HTML, text, Tweets, etc.) and building a scalable and flexible data pipeline that can ingest, analyse, normalise and summarise all these signals.

We decided to use Python to hook up all the components of our stack. At the core of our data application lies spaCy, which is the natural language processing engine enabling the extraction of meaningful information from large amounts of textual data.

We will present our workflow at a conceptual level (collecting data, textual analysis, creating insights). We will then describe the different components of our stack and why we chose them (Mongo, ElasticSearch, spaCy, AWS). Finally, we will share the lessons we have learned along the way on this challenging journey. Examples and code illustrating the main points will also be discussed during the talk.

**Comment by astrojuanlu** [comment]
@javipalanca está revisando. @python-spain/pycones-2018, si necesitáis el markdown de la primera charla para el estilo, avisad.

**Comment by javipalanca** [comment]
done!

**Comment by saruba** [comment]
Todo actualizado!
