### ISSUE TITLE
Repositorio Taller TDD

### ISSUE THREAD

**Issue by raulvillares** [python-spain/PyConES-2018#117]
Hola, 

hemos creado un repo con toda la info necesaria para los asistentes: https://github.com/aleasoluciones/pycones2018

https://2018.es.pycon.org/talk/tdd-de-cero-a-cien-o-casi

gracias!

**Comment by saruba** [comment]
Te lo añado al final de la descripción tal cual o ponemos algo mas descriptivo?
Algo como "Desde este repo podéis seguir los pasos de la instalación".

**Comment by raulvillares** [comment]
Sí, mejor algo más descriptivo:

_En este repositorio podéis encontrar todos los detalles e instrucciones para seguir el taller._

Muchas gracias!

**Comment by saruba** [comment]
Está actualizado, cualquier cosa nos dices.
