### ISSUE TITLE
Horarios Hackathon PyConES 2018

### ISSUE THREAD

**Issue by PyConEsHackathon** [python-spain/PyConES-2018#119]
Horarios a añadir en el schedule:

- Sábado 6 de Octubre - 19:30: Hackathon PyConES 2018 Happy Hour Contest
- Domingo 7 de Octubre - 10:30: Hackathon PyConES 2018 Accuracy Contest Solutions
- Domingo 7 de Octubre - 17:30: Hackathon PyConES 2018 Award ceremony

**Comment by astrojuanlu** [comment]
No hacer nada con esto hasta nuevo aviso.

**Comment by astrojuanlu** [comment]
Actualizado con la información nueva, ahora sí @python-spain/pycones-2018

**Comment by astrojuanlu** [comment]
@PythonHack18 recordad cambiaros el nombre :wink:

**Comment by PyConEsHackathon** [comment]
Jajaja, correcto ;)

**Comment by PyConEsHackathon** [comment]
Hola,

Disculpa que quedarían dos cosas:
- Cambiar en el opening de "Presentación PythonHack 2018" a "Presentación Hackathon PyConES 2018". 
- Poner un link a "https://hackathon.kernel-analytics.com/event/Hackathon-2018/" allá donde ponga "Hackathon PyConEs 2018"  (ojo que no es el mismo link que había antes en "Presentación PythonHack 2018")

Gracias!

**Comment by saruba** [comment]
Actualizado!
