### ISSUE TITLE
Oferta Orange

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#123]
[BigData_Orange_PyCon18.docx](https://github.com/python-spain/PyConES-2018/files/2446404/BigData_Orange_PyCon18.docx)

«Lo bueno de dejar las cosas para el último minuto es... ¡que solo tardas un minuto!»

**Comment by astrojuanlu** [comment]
"la oferta de Trabajo la pones como Data Scientist y como Data Engineering  y como Data Viz"

**Comment by saruba** [comment]
No entiendo nada, un docx? xD
Creo tres ofertas con el mismo detalle?

**Comment by astrojuanlu** [comment]
Bueno, o una sola oferta con una position "Data Scientist / Engineer / Viz"
