### ISSUE TITLE
Cambio de idioma en una charla

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#40]
Nos avisa @mariamedp que

> Os escribo porque, revisando la agenda en la web, he visto que mi charla pone que es en inglés, pero en realidad es en español. No sé si es un error o que me equivoqué en el C4P :/
Es la de "Prediciendo la contaminación del aire en Madrid: el proceso", el sábado 6 a las 18.00 en el track 1.

Error mío en la transcripción interna, con toda seguridad :)

**Comment by saruba** [comment]
O error mio en el copia y pega :)

**Comment by mariamedp** [comment]
Gracias!
