### ISSUE TITLE
Error en horas de la agenda

### ISSUE THREAD

**Issue by sdelquin** [python-spain/PyConES-2018#47]
El día 6 de octubre, después de la comida, creo que hay un error en las horas:
![captura de pantalla 2018-08-08 a las 18 05 23](https://user-images.githubusercontent.com/1591599/43852712-d3ba1236-9b35-11e8-86a5-bc7886c6ac03.png)
> La segunda tanda debería empezar a las 16:00h, ¿no?

**Comment by saruba** [comment]
Arreglado. Gracias por reportar!
