### ISSUE TITLE
Cambiar charla de Sara Iris a español

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#54]
Nos pide @montjoile que cambiemos su charla a español. @montjoile, necesitaríamos que actualizaras la descripción y el abstract en Papercall.

**Comment by saruba** [comment]
La charla está en español, falta actualizar la descripción.

**Comment by saruba** [comment]
@montjoile , si puedes pásanos por aquí los datos.

**Comment by astrojuanlu** [comment]
Título: Diseñando APIs en instantes usando Flask 

Abstract: Conoce Flask y cómo crear hermosas API REST en muy poco tiempo. Enamórate de Flask y aprende las mejores prácticas para construir APIs rápidamente.

Descripcion: Flask es un micro-framework liviano para Python. Su simplicidad y elasticidad lo convierten en la mejor opción para crear APIs en poco tiempo. En mi charla, cubriré los conceptos básicos de Flask y Requests. Mostraré las herramientas que pueden automatizar las tareas más comunes en el desarrollo de APIs y compartiré los patrones de diseño para evitar errores comunes. Algunas de las herramientas y temas específicos que cubriré: Flask-Restplus, SQLAlchemy, ciclo de vida de los requests, patrones de diseño de APIs REST + CRUD, arquitectura Flask.
