### ISSUE TITLE
Charla patrocinada Kaleidos

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#55]
Título: El hombre pisó la luna, pero gracias a la mujer
Ponente: Teresa de la Torre
Abstract: Si las primeras programadoras eran todas mujeres ¿cómo hemos llegado a ser sólo un 12% en las aulas de informática y tan pocas trabajando en este sector? Todo tiene un porqué y os lo voy a mostrar. Además vais a conocer a estupendas mujeres que no os imagináis lo que aportaron a la tecnología :)
Descripción: La mujer ha quedado siempre olvidada en los libros de historia, ciencia, arte o literatura; ha quedado oculta para el conocimiento popular. En la rama de la tecnología esto no ha sido diferente, y la tecnología se ha entendido como “cosa de hombres”. ¡Nada más lejos de la realidad! Os voy a enseñar cómo la tecnología no sería lo que es sin la crucial aportación de mujeres. Os voy a explicar porqué las primeras programadoras de la historia eran mujeres y ahora en cambio somos tan pocas. Porque todo tiene un porqué y porque no podemos seguir ignorando este problema. Tenemos que hacer algo ¡Y podemos hacerlo!
Bio: Curiosa y muy activa por naturaleza​. ​En los últimos 10 años, me he formado como programadora y he co-fundado dos empresas. También he sido consciente de la brecha de género en las empresas de mi sector, lo que me ha impulsado a participar en iniciativas que traten de acercar más mujeres a la tecnología, como talleres de iniciación o charlas que dan visibilidad a la labor de tantas mujeres. En mi tiempo libre, persigo quimeras con mi arco a lomos de mi caballo.

**Comment by javipalanca** [comment]
6 de Octubre - 12.30 - Tack 2

**Comment by saruba** [comment]
Le he puesto "Educación" como categoría.
