### ISSUE TITLE
Mover charla de Martina Kienberger a "Educación"

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#56]
Al principio entendí que la charla sería sobre Procesamiento de Lenguaje Natural y por eso la pusimos en Machine Learning, pero nos ha pedido la ponente que la cambiemos para reflejar mejor el contenido de la charla:

> [E]n mi charla voy a hablar más de cómo fue mi proceso de aprendizaje, qué herramientas me parecen útiles desde el punto de vista de alguien de ciencias sociales, etc.

Creo que lo mejor será ponerla en la categoría de Educación. @javipalanca, ¿crees que hará falta moverla de sitio para no "cortar" las charlas de Machine Learning? Lo dejo en tus manos.

**Comment by javipalanca** [comment]
Yo cambiaría la categoría sin moverla de sitio. Una vez publicada la agenda es un rollo cambiarla porque la gente ya se va haciendo planes, etc. Un pequeño corte en el track no molesta.
