### ISSUE TITLE
Añadir a Alberto Asuero y Cayetano Benavent como ponentes a la charla "Motor de optimización de rutas"

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#61]
Name: Josema Camacho
Bio: Josema ❤ Data, Betis & coffee, ¿en ese orden?. Se levanta a las 4 de la mañana por el Machine Learning y las metaheurísticas. Chief Innovation Officer en Geographica.

Name: Alberto Asuero
Twitter Handle: @alasarr
Organization or Affiliation: Geographica 
Bio: Alberto trata de conquistar el mundo usando mapas. Ha pedido días de 72 horas. Chief Technology Officer en Geographica.

Name: Cayetano Benavent
Twitter Handle: @cayetanobv
Organization or Affiliation: Geographica
Bio: Cayetano es un amante de los mapas, los datos y el open source software, especialmente si está escrito en Python. Head of Data en Geographica.

**Comment by saruba** [comment]
Están añadidos los ponentes, falta actualizar los datos en el detalle.

**Comment by saruba** [comment]
Los datos están actualizados en el csv.

**Comment by cayetanobv** [comment]
Hola @saruba , veo que en la web ha habido una regresión. Habías actualizado bien los ponentes que se pedían en esta issue, pero al meter el detalle han desaparecido otra vez. ¿Quizás ha sido al volver a importarlos?:
https://github.com/python-spain/PyConES-2018/commit/9225e0006f12e9f508629e68872074e8017a18cc

**Comment by saruba** [comment]
Si, culpa mía, al añadir los detalles hemos cambiado la fuente de datos.
Ya esta arreglado, cuando actualicemos el servidor saldréis lo tres.
La dejo abierta hasta que puedas comprobarlo en la web.

**Comment by cayetanobv** [comment]
Muchas gracias @saruba por la extrema rapidez!

**Comment by cayetanobv** [comment]
Ok @saruba , ya se ve en la web. Gracias.

**Comment by saruba** [comment]
Muchas gracias a ti por avisar.
