### ISSUE TITLE
Charla patrocinada Ravenpack

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#62]
Nombre de los Ponentes: Oscar Ramirez and Victoria Caparros

Titulo de la Charla: From unstructured news to real-time visualizations, a Fintech story

Resumen: 

In Fintech selecting the right technologies is as important as having the best ideas.

In this talk we will present how Ravenpack, one of the most important Big Data analytics providers for financial services, transforms unstructured documents into real-time visualizations. More precisely, we will focus on how we use Python to support the process.

**Comment by javipalanca** [comment]
6 de Octubre - 12.30 - Tack 1
