### ISSUE TITLE
https://es.pycon.org/ redirige a la edición de 2017

### ISSUE THREAD

**Issue by kikocorreoso** [python-spain/PyConES-2018#7]
SI ya está activa la página de 2018, como así parece, se debería apuntar es.pycon.org a 2018.es.pycon.org.

**Comment by astrojuanlu** [comment]
Gracias @kikocorreoso, nos lo han avisado también por Telegram. Encima tiene un certificado autofirmado... voy a hablar con @jcea para arreglar esto.

**Comment by astrojuanlu** [comment]
Perdón, hay dos problemas: https://es.pycon.org tiene un error HTTPS, y http://es.pycon.org redirige a 2017.

**Comment by astrojuanlu** [comment]
¡Arreglado!
