### ISSUE TITLE
Feedback sobre el idioma de la charla "Hacking Reinforcement Learning"

### ISSUE THREAD

**Issue by Guillemdb** [python-spain/PyConES-2018#78]
Buenas! Os escribo para preguntaros sobre el idoma en el que dar mi charla "Hacking Reinforcement Learning".  En su momento mandé el abstract en inglés comentando que a ser posible me gustaría darla en español. 

No se si aun tengo libertad para poder elegir el idoma o contais con que sea en inglés. Personalmente prefiero darla en español, pero no tengo problema en darla en ingles si ya contabais con ello. 

Por favor, puede alguien confirmarme en que idioma tengo que dar la charla?

**Comment by saruba** [comment]
La convierto a Español sin problema.
Envíanos la descripción en castellano y así la actualizo.

**Comment by Guillemdb** [comment]
Muchas gracias! Sorry por no contestar antes, no se que he hecho que no me llegan las notificaciones. Hoy sin falta dejo el abstract en español actualizado 😊

**Comment by Guillemdb** [comment]
He actualizado el abstract en Papercall.io. Os lo cuelgo aquí también o ya lo actualizais vosotros?

**Comment by astrojuanlu** [comment]
Si nos lo cuelgas aquí, estará actualizado más rápido - tengo un poco de atraso de emails :)

**Comment by Guillemdb** [comment]
## Titulo traducido
Hackeando el Reinforcement Learning
## Abstract corto
A pesar de los recientes avances en el campo del aprendizaje por refuerzo, generar fácilmente datasets de ejemplos de calidad sobrehumana sigue siendo un auténtico infierno. Por suerte, si nos permitimos hacer un poco de trampas y utilizar algoritmos de planificación, es posible conseguirlo.
# Abstract completo:
A pesar de los recientes avances en el campo del aprendizaje por refuerzo (Reinforcement Learning), generar fácilmente datasets de ejemplos de buena calidad sigue siendo un auténtico infierno. Por suerte, si nos permitimos hacer un poco de trampas y utilizar algoritmos de planificación, es posible conseguirlo. En hackeando el Reinforcement Learning, presentaremos una [nueva familia  de algoritmos de planificación](https://github.com/FragileTheory/FractalAI) capaces de obtener puntuaciones sobrehumanas utilizando muy pocos recursos de computación. 

El objetivo de esta charla es ofrecer una explicación intuitiva de cómo funciona esta nueva familia de algoritmos mediante animaciones visuales y demostraciones en vivo. Esta charla estará dividida en cuatro apartados que se corresponden con los pasos a seguir para hackear cualquier sistema.

1. **Recopilación de información**: En esta es una breve introducción a los conceptos necesarios para poder seguir la charla y entender el probema que queremos resolver.

2. **Escaneo y detección de vulnerabilidades**: Aquí explicaremos con animaciones visuales y sin entrar en detalles matemáticos en qué consisten los nuevos algoritmos presentados y cómo se integran con el aprendizaje por refuerzo.

3. **Explotación del sistema**: Python ofrece una gran cantidad de librerias y herramientas para trabajar con problemas de aprendizaje por refuerzo. En esta sección realizaremos una prueba de concepto en la que mostraremos como generar partidas de Ms.Pacman de calidad sobrehumana en tan solo unos minutos. Además, se mostraran ejemplos de como integrar los algoritmos presentados con las liberías ya existentes.

4. **Mantener el acceso y gestionar huellas**: Por último, se explicará que tipo de problemas pueden ser resueltos eficientemente, qué resultados hemos obtenido en diferentes pruebas, y dónde encontrar recursos adicionales para aprender más sobre el tema.

Esta charla es una adaptación de [Hacking reinforcement learning](https://github.com/Guillemdb/hacking-rl), presentada en EuroPython2018.

**Comment by saruba** [comment]
Actualizado
