### ISSUE TITLE
El botón para comprar las entradas muestra el texto en inglés

### ISSUE THREAD

**Issue by sdelquin** [python-spain/PyConES-2018#8]
En la versión española aparece esto:
![image](https://user-images.githubusercontent.com/1591599/39204890-0acfa634-47f1-11e8-9ed0-6fb8464c87cd.png)
Creo que es sólo cuestión de volver a compilar los mensajes:
`python manage.py compilemessages`

**Comment by danipv** [comment]
Gracias @sdelquin, efectivamente parece que los .mo no estaban actualizados.

**Comment by sdelquin** [comment]
Creo que sigue sin estar bien. Un ejemplo es el siguiente:
https://github.com/python-spain/PyConES-2018/blob/master/locale/es/LC_MESSAGES/django.po#L59

Ahí aparece `increíble` con tilde, pero en la web sigue apareciendo:
![captura de pantalla 2018-04-25 a las 16 42 18](https://user-images.githubusercontent.com/1591599/39256788-b29489e6-48a7-11e8-987c-9db625fdc360.png)

Da la sensación de que no se ha compilado el `django.po` o, si se ha compilado, no se ha desplegado correctamente.
