### ISSUE TITLE
Charla patrocinada Fever

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#92]
Abstract: Twelve-Factor app es una metodología de desarrollo de aplicaciones y servicios web. Aplicarla a nuestros proyectos en Python nos permite interactuar con las soluciones de ejecución en la nube más punteras.
Descripción: 

Twelve-Factor app es una metodología de desarrollo de aplicaciones y servicios web.

Su objetivo es homogeneizar los procesos de diseño, implementación y despliegue de forma que interactúen correctamente con las nuevas soluciones disponibles basadas en contenedores y clusters autogestionados (Heroku, OpenShift…).

Adicionalmente, genera una serie de beneficios inmediatos muy valiosos a nivel de DevOps.

Aplicar la metodología “Twelve-Factor app” a Python es a veces es complicado y controvertido. En esta charla discutiremos los desafíos que esta forma de trabajar presenta.

**Comment by astrojuanlu** [comment]
Autor: Francisco José Fernández Naranjo

**Comment by saruba** [comment]
Esto lo meto el 6 de octubre a las 12:30, como categoría DevOps y el track 3.

**Comment by saruba** [comment]
Le meto de titulo "Twelve-Factor app"
