### ISSUE TITLE
Oferta Paradigma

### ISSUE THREAD

**Issue by astrojuanlu** [python-spain/PyConES-2018#94]
https://www.linkedin.com/jobs/cap/view/850311814/?pathWildcard=850311814&trk=job_capjs

**Comment by saruba** [comment]
Creo que esa oferta es la misma que esta:
https://2018.es.pycon.org/jobs/paradigma-django-developer

Creo que antes de hacer el detalle de trabajo Andrea le pidió links externos.
Que hacemos, la añadimos, la sustituimos o la dejamos como esta?

**Comment by astrojuanlu** [comment]
Lo siento, pensaba que estábamos pidiendo links porque no podíamos meter el texto en la web. Ahora me parece un poco inconsistente que unas estén ahí y otras no, pero es un problema menor.

Dejemos el issue abierto y no hagamos nada de momento.

**Comment by saruba** [comment]
Ana me ha pasado otra vez la oferta y hemos pensado que la ponemos en el link del detalle.
Si nos llega un link para la otra oferta de paradigma cambiamos las dos como links externos, pero mientras lo dejaremos así.

**Comment by saruba** [comment]
La cierro y si nos llegase el otro link cambiamos las dos.
